
project_id = "wcezrgcmdrheyacsyimv"
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "send-email"
verify_jwt = false

[[functions]]
name = "verify-email-code"
verify_jwt = false

[[functions]]
name = "resend-verification-code"
verify_jwt = false

[[functions]]
name = "send-coparent-invite"
verify_jwt = false
