
# This config file defines the behavior of Supabase Edge Functions
project_id = "wcezrgcmdrheyacsyimv"

[functions.calendar-sync]
verify_jwt = false

[functions.co-parent-invites]
# Note: This function would handle co-parent invite operations
verify_jwt = true
